
CREATE TABLE IF NOT EXISTS worker
(
    ID INT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2),
    BIRTHDAY DATE CHECK (EXTRACT(YEAR FROM BIRTHDAY) > 1900),
    LEVEL VARCHAR(10) NOT NULL CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY INT CHECK (SALARY >= 100 AND SALARY <= 100000)
);

CREATE TABLE IF NOT EXISTS client
(
    ID INT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2)
);

CREATE TABLE IF NOT EXISTS project
(
    ID INT PRIMARY KEY,
    CLIENT_ID INT REFERENCES client(ID),
    START_DATE DATE,
    FINISH_DATE DATE
);

CREATE TABLE IF NOT EXISTS project_worker
(
    PROJECT_ID INT REFERENCES project(ID),
    WORKER_ID INT REFERENCES worker(ID),
    PRIMARY KEY (PROJECT_ID, WORKER_ID)
);